name: benchmark
on: [pull_request]
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build io_size helper
        run: g++ -std=c++17 -O2 -s -o measure_io/io_size measure_io/io_size.cpp
      - name: build OpenFHE
        run: ./scripts/get-openfhe.sh
      - name: find first submission folder
        id: sub
        run: echo "path=$(ls -d workloads/*/submissions/*/* | head -1)" >> $GITHUB_OUTPUT
      - name: run harness for detected workload
        run: |
          python3 $(dirname "${{ steps.sub.outputs.path }}")/../harness/run_submission.py \
            ${{ steps.sub.outputs.path }}
      - uses: actions/upload-artifact@v4
        with: {name: results, path: '**/results.json'}
